---
- name: "Download Kibana's deb"
  get_url:
    url: "https://artifacts.elastic.co/downloads/kibana/kibana-{{ kibana_version }}-amd64.deb"
    dest: "files/kibana-{{ kibana_version }}-amd64.deb"
  delegate_to: localhost
  register: download_kibana
  until: download_kibana is succeeded
  when: kibana_install_type == 'remote'
- name: Copy Kibana's deb to managed node
  copy:
    src: "files/kibana-{{ kibana_version }}-amd64.deb"
    mode: 0744
    dest: "/tmp/kibana-{{ kibana_version }}-amd64.deb"